### PR TITLE
Remove time selection form RangePicker to only select dates

### PR DESCRIPTION
**Pull request by asylbek09**

### CODE REVIEW

**Comment by asylbek09** [comment]
Issue: https://github.com/InetIntel/ioda-ui/issues/113

**Comment by salcock** [comment]
Would it be possible to reset the "time" to 00:00 UTC at the start of the day when choosing the start date, and to 00:00 UTC for the following day when choosing an end date?

As opposed to the current method, where the "time" is just whatever it was previously set to (usually the time when you loaded the page), e.g. if I go to the page at 11:34pm UTC and then choose a date range, I end up with a graph that ranges from <start date> 11:34pm to <end date> 11:34pm -- I would miss out on most of the signal for the start date that I chose.

@amandahmeng do you agree?

**Comment by asylbek09** [comment]
Sounds like a good idea. Let me update that

**Comment by asylbek09** [comment]
Screenshot 2024-03-06 at 10 58 36

Attached screenshot, when selecting dates from RangePicker Date/Time updated to 00:00 UTC

**Pull request merged**
